return {
    { Name = "AtherHub [KEY]", URL = "https://scriptblox.com/raw/Blox-Fruits-Atherhub-Auto-Level-Auto-Raid-Auto-Boss-BEST-Script-79550" },
    { Name = "Forge Hub [KEY]", URL = "https://scriptblox.com/raw/Control-Blox-Fruits-OP-FREE-GUI-77953" },
    { Name = "Lumin Hub [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Lumin-Hub-Kill-without-Tween-and-keyless-140587" },
    { Name = "Cursed Hub [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Cursed-Hub-216708" },
    { Name = "Anonim 1 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-OP-SCRIPT-KEYLESS-WITH-ITEM-S*ER-216610" },
    { Name = "Anonim 2 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Best-Auto-Raid-and-kill-aura-216605" },
    { Name = "Anonim 3 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Op-Auto-Farm-Auto-Raid-216523" },
    { Name = "Anonim 4 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Autofarm-Kill-Aura-Auto-Unlock-Sea-2-Auto-PVP-MORE-214756" },
    { Name = "Anonim 5 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-sailor-auto-farm-auto-quest-fast-level-adventure-script-216348" },
    { Name = "Anonim 6 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-sailor-auto-farm-auto-quest-fast-level-adventure-script-216348" },
    { Name = "Anonim 7 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Autofarm-Kill-Aura-Auto-Unlock-Sea-2-Auto-PVP-216310" },
    { Name = "Anonim 8 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Spam-No-Cd-Skills-l-Auto-2nd-Sea-l-And-more-216094" },
    { Name = "Anonim 9 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Auto-Raid-Auto-Quests-215881" },
    { Name = "Anonim 10 [KEY]", URL = "https://scriptblox.com/raw/Alter-Update-Sailor-Piece-BEST-SCRIPT-AUTOFARM-MOB-AUTO-USE-SKILL-AND-MUCH-MORE-134404" },
    { Name = "Anonim 11 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Best-Script-For-Afk-Auto-Farming-215868" },
    { Name = "Anonim 12 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-sailor-auto-farm-auto-quest-fast-level-adventure-script-215685" },
    { Name = "Anonim 13 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-OP-GUI-FULL-AFK-AUTOFARM-215671" },
    { Name = "Anonim 14 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-INF-Money-and-Dupe-Much-MORE-215592" },
    { Name = "Anonim 15 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Spam-No-Cd-Skills-l-Auto-2nd-Sea-l-And-more-215419" },
    { Name = "BlackHub [KEY]", URL = "https://scriptblox.com/raw/Massive-Update-Sailor-Piece-Blackhub-Auto-Farm-Level-Bosses-153605" },
    { Name = "Anonim 16 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Best-Working-Script-Autofarm-Free-136631" },
    { Name = "Lumin Hub v2 [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-Lumin-Hub-81656" },
    { Name = "Rift Hub [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-Rift-46927" },
    { Name = "Anonim 17 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Op-Raid-and-Lvl-Auto-Farm-215377" },
    { Name = "Ikat Hub [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-ikat-hub-best-hub-out-there-made-by-gio-215367" },
    { Name = "Anonim 18 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Item-Duper-215323" },
    { Name = "Anonim 19 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-OP-GUI-FULL-AFK-AUTOFARM-215230" },
    { Name = "Anonim 20 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-FULL-AFK-AUTOFARM-GUI-215082" },
    { Name = "Anonim 21 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-auto-kill-aimbot-auto-farm-second-sea-215029" },
    { Name = "Anonim 22 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-script-214993" },
    { Name = "Anonim 23 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Raid-Update-214963" },
    { Name = "Anonim 24 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Solix-Hub-214904" },
    { Name = "Anonim 25 [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-New-Best-Auto-Farm-214804" },
    { Name = "Anonim 26 [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-BEST-SCRIPT-KEYLESS-214794" },
    { Name = "Daiku Hub [KEYLESS]", URL = "https://scriptblox.com/raw/Universal-Script-DAIKU-HUB-BEST-DUPE-SCRIPT-206872" },
    { Name = "Anonim 27 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-NO-KEY-SYSTEM-AUTO-WIN-ESP-AUTO-FARM-214594" },
    { Name = "Anonim 28 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-NEW-BEST-OP-SCRIPT-AUTO-RAIDS-AND-AUTO-FARM-WORKING-214552" },
    { Name = "Nicuse Hub [KEYLESS]", URL = "https://scriptblox.com/raw/Universal-Script-Nicuse-Scripts-10-Games-43136" },
    { Name = "Anonim 29 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Auto-Farm-214478" },
    { Name = "Anonim 30 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-AUTO-MAX-INDEX-AUTO-RAID-AUTO-FARM-AUTO-BOSS-AUTO-TOWER-214428" },
    { Name = "KFCHook [KEY]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Sailor-KFCHook-214371" },
    { Name = "Express Hub [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Express-Hub-214250" },
    { Name = "Anonim 31 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Autofarm-Kill-Aura-Unlock-SEA-2-AND-More-Features-214227" },
    { Name = "ZayOHub [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-ZayO-Hub-Best-Script-Auto-Farm-214152" },
    { Name = "Klakuylek Hub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Klakuylek-Hub-201785" },
    { Name = "Anonim 32 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-AUTO-RAID-AUTO-GET-BEST-ARTIFACT-AND-MAXOUT-INDEX-AND-MORE-213905" },
    { Name = "Polluted Hub [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Polluted-Hub-213879" },
    { Name = "KRware Hub [KEYLESS]", URL = "https://scriptblox.com/raw/Universal-Script-KRware-hub-6-may-2026-213207" },
    { Name = "Anonim 33 [KEYLESS]", URL = "https://scriptblox.com/raw/Huge-Update-Sailor-Piece-Best-script-213891" },
    { Name = "Anonim 34 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Auto-Boss-Kill-Aura-GodMode-213688" },
    { Name = "Crazy Hub [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-CrazyHub-213391" },
    { Name = "Eternal Hub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-JUST-UPDATED-ETERNAL-Hub-Best-Script-RN-213325" },
    { Name = "Solved Hub [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-Solvex-Hub-Universal-Roblox-Script-Hub-138625" },
    { Name = "Rune Hub [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Rune-Hub-JUST-UPDATED-212955" },
    { Name = "Anonim 35 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Kill-Aura-Unlock-Sea-2-FULL-AUTOFARM-FRUIT-STATS-PVP-AND-MOR-213378" },
    { Name = "Horizon Hub [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-Horizon-Hub-Op-201990" },
    { Name = "Anonim 36 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Auto-Quest-Auto-fruit-and-more-212105" },
    { Name = "Anonim 37 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-AUTO-FARM-EVERYTHING-IN-SEA-2-SUPER-OP-AND-MORE-213243" },
    { Name = "Anonim 38 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Autofarm-auto-dungeon-instant-hit-kill-aura-Auto-quest-213143" },
    { Name = "Anonim 39 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Auto-Boss-Kill-Aura-GodMode-213101" },
    { Name = "GameHub [KEY]", URL = "https://scriptblox.com/raw/Universal-Script-Gamehuhhb-212958" },
    { Name = "Anonim 40 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-OP-GUI-FULL-AUTOFARM-AND-UNLOCK-SEA-2-212926" },
    { Name = "Anonim 41 [KEYLESS]", URL = "https://scriptblox.com/raw/Universal-Script-BEST-DUPE-SCRIPT-KEYLESS-212767" },
    { Name = "DoxHub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-dox-212695" },
    { Name = "Anonim 42 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Auto-Boss-Kill-Aura-GodMode-212575" },
    { Name = "Anonim 43 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-script-new-update-212434" },
    { Name = "Anonim 44 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Autofarm-Stats-Fruit-Skill-Unlock-Sea-2-Easter-Eggs-AND-MORE-212406" },
    { Name = "Anonim 45 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-AutoFarm-Item-Set-Kokushibo-IceQueen-ShadowV2-More-212319" },
    { Name = "Anonim 46 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Full-Autofarm-Unlock-Sea-2-Automation-AND-MORE-212182" },
    { Name = "Anonim 47 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-sailer-piece-dupe-script-212109" },
    { Name = "Anonim 48 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Autofarm-Max-Stats-Unlock-Sea-2-Auto-boss-AND-MORE-213209" },
    { Name = "Moon Hub [KEYLESS]", URL = "https://scriptblox.com/raw/Eat-the-World-MOON-HUB-212583" },
    { Name = "Anonim 49 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Auto-Farm-212529" },
    { Name = "Anonim 50 [KEY]", URL = "https://scriptblox.com/raw/Sea-2-Update-Sailor-Piece-Auto-Farm-Max-Level-203483" },
    { Name = "Anonim 51 [KEY]", URL = "https://scriptblox.com/raw/Anti-Magic-Update-Sailor-Piece-Sea-2-Instant-Tp-Auto-Quest-Max-Level-nmore-208371" },
    { Name = "Anonim 52 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-script-auto-farm-no-key-212468" },
    { Name = "Anonim 53 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Full-Autofarm-GUI-Killaura-212320" },
    { Name = "LuxvsHub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-LuxvsHub-211956" },
    { Name = "Anonim 54 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-FULL-AUTOFARM-AFK-211891" },
    { Name = "Anonim 55 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Auto-Farm-Max-Level-211666" },
    { Name = "Anonim 56 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-MAX-Stats-Autofarm-AFK-211369" },
    { Name = "ForkyHub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-ForkyHUB-Script-Autofarm-TradeGUI-MORE-211363" },
    { Name = "Anonim 57 [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-KEYLESS-KAITUN-AUTOFARM-AND-INSTANT-KILL-211293" },
    { Name = "Astro Hub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Astro-Hub-211284" },
    { Name = "Nah Hub [KEYLESS]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-NAH-HUB-211193" },
    { Name = "Anonim 58 [KEY]", URL = "https://scriptblox.com/raw/2x-Luck-Sailor-Piece-Best-Script-211103" }
}

